version: '2'
services:
  referential-postgresql:
    network_mode: 'host'
    image: postgres:11.1
    # volumes:
    #     - ~/volumes/jhipster/referential/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=referential
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
